function identify_gaoptimset(generations,populations,tolfun)
global dirname;
dirname = 'c:\Users\tomaton\Documents\KOFRLAB-simenv\VersionedProjects\';
 global filename;
 filename = strcat(dirname,'matlab.log');
global gaoptions;
gaoptions = gaoptimset(...
    'Vectorized','on',...
    'TolFun',tolfun,...
    'Generations',generations,...
    'PopulationSize',populations);
identify_log('gaoptimse tolfun generations populations',{tolfun generations populations});
