function identify_gaoptimset(generations,populations,tolfun)

global gaoptions;
gaoptions = gaoptimset(...
    'Vectorized','on',...
    'TolFun',tolfun,...
    'Generations',generations,...
    'PopulationSize',populations);
identify_log('gaoptimse tolfun generations populations',{tolfun generations populations});
