//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMUSingleNodeWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMUSingleNodeWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Allow HTTP listen e.g. on Windows Server platform with
        ///: netsh http add urlacl url=http://{0}:{1}/  user=\Everyone listen=yes.
        /// </summary>
        public static string AppHost_Start_ {
            get {
                return ResourceManager.GetString("AppHost_Start_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deregister this worker on URL {0}..
        /// </summary>
        public static string Program_degisterRESTWorker_Cannot_deregister_this_worker_on_URL__0__ {
            get {
                return ResourceManager.GetString("Program_degisterRESTWorker_Cannot_deregister_this_worker_on_URL__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deregistered worker id {0} on {1}.
        /// </summary>
        public static string Program_degisterRESTWorker_Deregistered_worker_id__0__on__1_ {
            get {
                return ResourceManager.GetString("Program_degisterRESTWorker_Deregistered_worker_id__0__on__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected IP address {0}..
        /// </summary>
        public static string Program_getCurrentIPAddress_Detected_IP_address__0__ {
            get {
                return ResourceManager.GetString("Program_getCurrentIPAddress_Detected_IP_address__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter, type -h for help..
        /// </summary>
        public static string Program_Main_Missing_required_parameter__type__h_for_help_ {
            get {
                return ResourceManager.GetString("Program_Main_Missing_required_parameter__type__h_for_help_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register this worker on URL .
        /// </summary>
        public static string Program_registerRESTWorker_Cannot_register_this_worker_on_URL_ {
            get {
                return ResourceManager.GetString("Program_registerRESTWorker_Cannot_register_this_worker_on_URL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered worker id {0} on {1}..
        /// </summary>
        public static string Program_registerRESTWorker_Registered_worker_id__0__on__1__ {
            get {
                return ResourceManager.GetString("Program_registerRESTWorker_Registered_worker_id__0__on__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to stop the server ....
        /// </summary>
        public static string Program_runHttpServer_Press_any_key_to_stop_the_server____ {
            get {
                return ResourceManager.GetString("Program_runHttpServer_Press_any_key_to_stop_the_server____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppHost Created at {0}, listening on {1}.
        /// </summary>
        public static string Program_startHttpServer_AppHost_Created_at__0___listening_on__1_ {
            get {
                return ResourceManager.GetString("Program_startHttpServer_AppHost_Created_at__0___listening_on__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppHost starting to listen on {0}.
        /// </summary>
        public static string Program_startHttpServer_AppHost_starting_to_listen_on__0_ {
            get {
                return ResourceManager.GetString("Program_startHttpServer_AppHost_starting_to_listen_on__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded model {0}..
        /// </summary>
        public static string Program_startHttpServer_Loaded_model__0__ {
            get {
                return ResourceManager.GetString("Program_startHttpServer_Loaded_model__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FMUSingleNodeWrapper [params]
        ///
        ////f=[file_name] REQUIRED, filename or full path to FMU 
        ////t=[temp_directory] optional, temporary directory with read/write permission to unpack FMU
        ////p=[port_number] optional, sets the embeded HTTP server port number
        ////u=[host_name_or_IP] optional, sets hostname or IP address to listen, by default it is detected by system
        ////w=[register_worker_url] optional, sets URL of REST Worker service to register this worker
        ////h		will show this help
        ///.
        /// </summary>
        public static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
    }
}
